# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 02:39
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.FloatField(default=0.0)),
                ('title', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('imgae', models.ImageField(blank=True, null=True, upload_to=accounts.models.HomeDetails.home_image)),
            ],
        ),
        migrations.CreateModel(
            name='HomeRentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HomeDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.TextField(blank=True, max_length=128, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homerentdetails',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='homedetails',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
