# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171221_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
